Question 2: Convolution Operations with Different Parameters (20 points)

Task: Implement Convolution with Different Stride and Padding (10 points)

Write a Python script using NumPy and TensorFlow/Keras to perform convolution on a 5×5 input matrix using a 3×3 kernel with varying parameters.

1.	Define the following 5×5 input matrix:
 
2.	Define the following 3×3 kernel:
 
3.	Perform convolution operations with:

o	Stride = 1, Padding = ‘VALID’

o	Stride = 1, Padding = ‘SAME’

o	Stride = 2, Padding = ‘VALID’

o	Stride = 2, Padding = ‘SAME’

4.	Print the output feature maps for each case.

Expected Output

Print the output feature maps for

o	Stride = 1, Padding = ‘VALID’
o	Stride = 1, Padding = ‘SAME’
o	Stride = 2, Padding = ‘VALID’
o	Stride = 2, Padding = ‘SAME’



In [5]:
import numpy as np
import tensorflow as tf

# Define the 5x5 input matrix
input_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

# Define the 3x3 kernel
kernel = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
], dtype=np.float32)

# Reshape input to match TensorFlow's format: 
input_tensor = input_matrix.reshape((1, 5, 5, 1)) #(batch, height, width, channels)
kernel_tensor = kernel.reshape((3, 3, 1, 1))  #(filter_height, filter_width, in_channels, out_channels)

# Function to perform convolution
def perform_convolution(stride, padding):
    result = tf.nn.conv2d(
        input=input_tensor,
        filters=kernel_tensor,
        strides=[1, stride, stride, 1],
        padding=padding
    )
    return result.numpy().squeeze()

# Perform and print results
print("Stride = 1, Padding = 'VALID':\n", perform_convolution(1, 'VALID'))
print("\nStride = 1, Padding = 'SAME':\n", perform_convolution(1, 'SAME'))
print("\nStride = 2, Padding = 'VALID':\n", perform_convolution(2, 'VALID'))
print("\nStride = 2, Padding = 'SAME':\n", perform_convolution(2, 'SAME'))

Stride = 1, Padding = 'VALID':
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Stride = 1, Padding = 'SAME':
 [[  4.   3.   2.   1.  -6.]
 [ -5.   0.   0.   0. -11.]
 [-10.   0.   0.   0. -16.]
 [-15.   0.   0.   0. -21.]
 [-46. -27. -28. -29. -56.]]

Stride = 2, Padding = 'VALID':
 [[0. 0.]
 [0. 0.]]

Stride = 2, Padding = 'SAME':
 [[  4.   2.  -6.]
 [-10.   0. -16.]
 [-46. -28. -56.]]
